// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3uxiGUrkjZrN4FbnTSmGtJj-RfmE2xjM',
    appId: '1:802254430913:web:e7809bf02dd7983d1bea40',
    messagingSenderId: '802254430913',
    projectId: 'tymko-15786',
    authDomain: 'tymko-15786.firebaseapp.com',
    storageBucket: 'tymko-15786.firebasestorage.app',
    measurementId: 'G-CGMHBKJCK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4xZ4cXU0a-5EVcq75UIKbKbwGKa0G3qs',
    appId: '1:802254430913:android:7074e239845c6e331bea40',
    messagingSenderId: '802254430913',
    projectId: 'tymko-15786',
    storageBucket: 'tymko-15786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGZiTeVX7bLrfxp_0KCvcXf26mxPqdyQM',
    appId: '1:802254430913:ios:33a62c5d3233ad651bea40',
    messagingSenderId: '802254430913',
    projectId: 'tymko-15786',
    storageBucket: 'tymko-15786.firebasestorage.app',
    iosBundleId: 'com.example.tymkoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGZiTeVX7bLrfxp_0KCvcXf26mxPqdyQM',
    appId: '1:802254430913:ios:33a62c5d3233ad651bea40',
    messagingSenderId: '802254430913',
    projectId: 'tymko-15786',
    storageBucket: 'tymko-15786.firebasestorage.app',
    iosBundleId: 'com.example.tymkoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3uxiGUrkjZrN4FbnTSmGtJj-RfmE2xjM',
    appId: '1:802254430913:web:92a002272c1d172c1bea40',
    messagingSenderId: '802254430913',
    projectId: 'tymko-15786',
    authDomain: 'tymko-15786.firebaseapp.com',
    storageBucket: 'tymko-15786.firebasestorage.app',
    measurementId: 'G-EWEM5XB6WD',
  );

}